version: "3.9"

services:
    app:
        build: .
        container_name: iris_api
        ports:
        - "8000:8000"
        depends_on:
        - db
        networks:
          - lab_network

    db:
        image: postgres:16
        container_name: iris_postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: iris_db
        ports:
        - "5432:5432"
        networks:
            - lab_network
        volumes:
          - postgres_data:/var/lib/postgresql/data
networks:
    lab_network:
        driver: bridge
volumes:
      postgres_data: